#!/usr/bin/env php
<?php

$url = 'https://github.com/asartalo/Silly.git';
$depsDir = realpath(__DIR__) . '/vendor/Silly';

echo "updating Silly in $depsDir\n";

if (!is_dir($depsDir)) {
    echo system(sprintf('git clone %s %s', escapeshellarg($url), escapeshellarg($depsDir)));
}

echo system(sprintf('cd %s && git pull origin master', escapeshellarg($depsDir)));
